<?php
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/functions.php';

$courseId = valid_id($_GET['id'] ?? null);
$course = null;
$syllabus = [];
$fees = [];
$errorMessage = null;

if ($courseId === null) {
	$errorMessage = empty($_GET['id']) ? 'Please select a course to view its details.' : 'The course ID is invalid.';
} else {
	$courseStatement = $pdo->prepare('SELECT id, title, slug, category, description, duration, level, image FROM courses WHERE id = :id AND status = :status LIMIT 1');
	$courseStatement->execute(['id' => $courseId, 'status' => 1]);
	$course = $courseStatement->fetch();

	if (!$course) {
		$errorMessage = 'The requested course could not be found.';
	} else {
		$syllabusStatement = $pdo->prepare('SELECT module_title, module_description, module_order FROM syllabus WHERE course_id = :course_id AND status = :status ORDER BY module_order, id');
		$syllabusStatement->execute(['course_id' => $courseId, 'status' => 1]);
		$syllabus = $syllabusStatement->fetchAll();

		$feesStatement = $pdo->prepare('SELECT fee_type, amount, discount_amount, duration, description FROM fees WHERE course_id = :course_id AND status = :status ORDER BY id');
		$feesStatement->execute(['course_id' => $courseId, 'status' => 1]);
		$fees = $feesStatement->fetchAll();
	}
}

$pageTitle = $course ? $course['title'] : 'Course Details';
$courseHighlights = [
	'website-development' => ['skills' => ['HTML5 and CSS3', 'Bootstrap responsive layouts', 'Core PHP and MySQL', 'PDO database integration'], 'benefits' => ['Build complete websites from scratch', 'Create a portfolio of real projects', 'Learn secure, beginner-friendly web development'], 'assignments' => ['Build a responsive academy landing page', 'Create a PDO-powered course catalog', 'Complete a final multi-page website'], 'quizzes' => ['HTML, CSS and responsive layout quiz', 'PHP, MySQL and security checkpoint']],
	'digital-marketing' => ['skills' => ['SEO fundamentals', 'Content and social media strategy', 'Email campaigns', 'Analytics and reporting'], 'benefits' => ['Grow brands across digital channels', 'Plan campaigns with measurable goals', 'Build practical marketing case studies'], 'assignments' => ['Create a 30-day content calendar', 'Perform an SEO audit for a sample website', 'Present a complete digital campaign'], 'quizzes' => ['Digital marketing fundamentals quiz', 'SEO and analytics checkpoint']],
	'graphic-designing' => ['skills' => ['Composition and typography', 'Brand identity design', 'Social media graphics', 'Design presentation'], 'benefits' => ['Create polished visual work', 'Develop a professional design portfolio', 'Turn creative ideas into client-ready designs'], 'assignments' => ['Design a personal brand identity', 'Create a social media campaign set', 'Present a complete visual portfolio'], 'quizzes' => ['Color, typography and composition quiz', 'Branding principles checkpoint']],
	'artificial-intelligence' => ['skills' => ['AI concepts and problem solving', 'Data preparation', 'Intelligent system design', 'Responsible AI thinking'], 'benefits' => ['Understand how modern AI works', 'Apply AI ideas to practical problems', 'Prepare for further technical study'], 'assignments' => ['Map an AI solution for a real problem', 'Prepare a small structured dataset', 'Design a responsible AI use case'], 'quizzes' => ['AI concepts and terminology quiz', 'Responsible AI checkpoint']],
	'machine-learning' => ['skills' => ['Data preparation', 'Supervised learning', 'Model evaluation', 'Practical ML workflows'], 'benefits' => ['Build confidence with data-driven solutions', 'Understand model performance', 'Create projects that demonstrate analytical thinking'], 'assignments' => ['Clean and prepare a sample dataset', 'Train a supervised learning model', 'Compare model results and write findings'], 'quizzes' => ['Data preparation quiz', 'Model evaluation checkpoint']],
	'cyber-security' => ['skills' => ['Security fundamentals', 'Threat awareness', 'Defensive practices', 'Responsible testing'], 'benefits' => ['Protect systems and digital accounts', 'Recognize common security risks', 'Build a foundation for security careers'], 'assignments' => ['Create a personal security checklist', 'Analyze a sample threat scenario', 'Write a defensive security improvement plan'], 'quizzes' => ['Security fundamentals quiz', 'Threat awareness checkpoint']],
	'python-programming' => ['skills' => ['Python syntax and logic', 'Functions and data structures', 'File handling', 'Project development'], 'benefits' => ['Build a strong programming foundation', 'Automate everyday tasks', 'Prepare for data, web and AI learning'], 'assignments' => ['Build a command-line utility', 'Create a file-based data tool', 'Complete a small Python project'], 'quizzes' => ['Python syntax and logic quiz', 'Functions and data checkpoint']],
	'ui-ux-design' => ['skills' => ['User research', 'Wireframing', 'Prototyping', 'Usability principles'], 'benefits' => ['Design clearer digital experiences', 'Build a UX case-study portfolio', 'Solve problems from the user’s perspective'], 'assignments' => ['Interview users for a sample product', 'Create a wireframe and user flow', 'Present a clickable prototype'], 'quizzes' => ['User research quiz', 'Usability and prototyping checkpoint']],
	'freelancing' => ['skills' => ['Profile and portfolio building', 'Client communication', 'Proposals and pricing', 'Professional delivery'], 'benefits' => ['Present your skills with confidence', 'Find and manage digital opportunities', 'Build sustainable freelance habits'], 'assignments' => ['Create a professional freelancer profile', 'Write a proposal for a sample project', 'Build a simple service pricing plan'], 'quizzes' => ['Freelance profile quiz', 'Client communication checkpoint']],
	'e-commerce' => ['skills' => ['Store planning', 'Product presentation', 'Online marketing', 'Customer and order workflows'], 'benefits' => ['Plan an online business', 'Understand the customer journey', 'Create practical e-commerce strategies'], 'assignments' => ['Plan a niche online store', 'Create product listings and categories', 'Design a launch and customer-care plan'], 'quizzes' => ['E-commerce foundations quiz', 'Customer journey checkpoint']],
	'video-editing' => ['skills' => ['Editing workflow', 'Storytelling and pacing', 'Audio and titles', 'Web-ready exporting'], 'benefits' => ['Create engaging digital videos', 'Build a media portfolio', 'Communicate ideas through visual storytelling'], 'assignments' => ['Edit a short story from raw clips', 'Create a titled social video', 'Export a final portfolio reel'], 'quizzes' => ['Editing workflow quiz', 'Audio and export checkpoint']],
	'database-management' => ['skills' => ['Relational database design', 'SQL queries', 'Keys and relationships', 'Safe PDO access'], 'benefits' => ['Organize data with confidence', 'Build reliable database-backed projects', 'Understand skills used in web applications'], 'assignments' => ['Design a relational course database', 'Write useful SQL reports', 'Connect a PHP form with PDO'], 'quizzes' => ['Database design quiz', 'SQL and safe access checkpoint']],
];
$highlights = $course ? ($courseHighlights[$course['slug']] ?? ['skills' => [], 'benefits' => [], 'assignments' => [], 'quizzes' => []]) : ['skills' => [], 'benefits' => [], 'assignments' => [], 'quizzes' => []];
require __DIR__ . '/includes/header.php';
?>
<?php if ($errorMessage): ?><section class="section-space"><div class="container"><div class="text-center py-5"><div class="icon-box mx-auto mb-3"><i class="bi bi-exclamation-circle"></i></div><h1 class="section-title">Course unavailable</h1><p class="text-secondary"><?= e($errorMessage) ?></p><a href="courses.php" class="btn btn-primary mt-2">Browse Courses</a></div></div></section>
<?php else: ?><section class="page-hero"><div class="container"><span class="eyebrow text-info"><?= e($course['category']) ?></span><h1 class="mt-3"><?= e($course['title']) ?></h1><p class="lead mb-0">Build practical skills with a clear, project-focused learning path.</p></div></section>
<section class="section-space"><div class="container"><div class="row g-5 align-items-start"><div class="col-lg-5"><?php if (!empty($course['image'])): ?><img src="<?= e(image_url($course['image'])) ?>" class="w-100 rounded-4 shadow-sm" style="min-height:280px;object-fit:cover" alt="<?= e($course['title']) ?>"><?php else: ?><div class="placeholder-image rounded-4" style="height:300px"><i class="bi bi-mortarboard"></i></div><?php endif; ?><div class="d-flex gap-3 mt-4"><a href="enrollment.php?course_id=<?= e($course['id']) ?>" class="btn btn-primary">Enroll Now <i class="bi bi-arrow-right"></i></a><a href="#syllabus" class="btn btn-outline-primary">View Syllabus</a></div></div><div class="col-lg-7"><span class="eyebrow">Course overview</span><h2 class="section-title mt-3"><?= e($course['title']) ?></h2><p class="section-copy mt-3"><?= nl2br(e($course['description'])) ?></p><div class="row g-3 mt-3"><div class="col-sm-6"><div class="info-card p-3"><small class="text-secondary d-block">Duration</small><strong><i class="bi bi-clock me-2 text-primary"></i><?= e($course['duration']) ?></strong></div></div><div class="col-sm-6"><div class="info-card p-3"><small class="text-secondary d-block">Level</small><strong><i class="bi bi-bar-chart me-2 text-primary"></i><?= e($course['level']) ?></strong></div></div></div></div></div><div class="row g-4 mt-4"><div class="col-lg-6"><div class="info-card h-100 p-4"><span class="eyebrow">What you will learn</span><h3 class="h4 mt-2">Skills you can use</h3><ul class="list-unstyled mb-0 mt-3"><?php foreach ($highlights['skills'] as $skill): ?><li class="mb-2"><i class="bi bi-check-circle-fill text-success me-2"></i><?= e($skill) ?></li><?php endforeach; ?></ul></div></div><div class="col-lg-6"><div class="info-card h-100 p-4"><span class="eyebrow">Why choose this course</span><h3 class="h4 mt-2">Benefits for your future</h3><ul class="list-unstyled mb-0 mt-3"><?php foreach ($highlights['benefits'] as $benefit): ?><li class="mb-2"><i class="bi bi-stars text-primary me-2"></i><?= e($benefit) ?></li><?php endforeach; ?></ul></div></div></div></div></section>
<section id="syllabus" class="section-space section-soft"><div class="container"><div class="row g-5"><div class="col-lg-7"><span class="eyebrow">Your learning path</span><h2 class="section-title mt-2">Course Syllabus</h2><?php if ($syllabus): ?><div class="accordion mt-4" id="syllabusAccordion"><?php foreach ($syllabus as $index => $module): ?><div class="accordion-item border-0 mb-2 rounded-3 overflow-hidden"><h2 class="accordion-header"><button class="accordion-button <?= $index !== 0 ? 'collapsed' : '' ?>" type="button" data-bs-toggle="collapse" data-bs-target="#module<?= e($index) ?>"><span class="badge badge-soft me-3"> <?= e($module['module_order']) ?> </span><?= e($module['module_title']) ?></button></h2><div id="module<?= e($index) ?>" class="accordion-collapse collapse <?= $index === 0 ? 'show' : '' ?>" data-bs-parent="#syllabusAccordion"><div class="accordion-body text-secondary"><?= nl2br(e($module['module_description'])) ?></div></div></div><?php endforeach; ?></div><?php else: ?><p class="text-secondary mt-4">The syllabus for this course will be published soon.</p><?php endif; ?></div><div class="col-lg-5"><span class="eyebrow">Invest in yourself</span><h2 class="section-title mt-2">Course Fees</h2><?php if ($fees): ?><div class="mt-4"><?php foreach ($fees as $fee): ?><div class="info-card p-4 mb-3"><div class="d-flex justify-content-between gap-3"><h5><?= e($fee['fee_type']) ?></h5><span class="badge bg-success-subtle text-success">Available</span></div><div class="d-flex align-items-baseline gap-2 my-2"><strong class="fs-3 text-primary">Rs. <?= e(number_format((float) $fee['amount'], 2)) ?></strong><?php if ((float) $fee['discount_amount'] > 0): ?><span class="text-secondary text-decoration-line-through small">Rs. <?= e(number_format((float) $fee['discount_amount'], 2)) ?></span><?php endif; ?></div><p class="small text-secondary mb-1"><i class="bi bi-calendar3 me-2"></i><?= e($fee['duration']) ?></p><?php if (!empty($fee['description'])): ?><p class="small text-secondary mb-0 mt-2"><?= e($fee['description']) ?></p><?php endif; ?></div><?php endforeach; ?></div><?php else: ?><p class="text-secondary mt-4">Fee details will be published soon.</p><?php endif; ?></div></div></div></section><?php endif; ?>
<section class="section-space"><div class="container"><div class="text-center mb-5"><span class="eyebrow">Learn by doing</span><h2 class="section-title mt-2">Your course experience</h2><p class="section-copy mx-auto">Every course combines lessons, practical work and quick knowledge checks so you can track your progress.</p></div><div class="row g-4"><div class="col-lg-6"><div class="learning-panel h-100 p-4 p-md-5"><div class="learning-icon"><i class="bi bi-clipboard-check"></i></div><h3 class="h4 mt-3">Practical assignments</h3><p class="text-secondary">Build useful work step by step and finish with evidence of what you can do.</p><ol class="learning-list"><?php foreach ($highlights['assignments'] as $assignment): ?><li><?= e($assignment) ?></li><?php endforeach; ?></ol></div></div><div class="col-lg-6"><div class="learning-panel learning-panel-alt h-100 p-4 p-md-5"><div class="learning-icon"><i class="bi bi-patch-question"></i></div><h3 class="h4 mt-3">Quizzes and checkpoints</h3><p class="text-secondary">Use short quizzes to reinforce key ideas before moving to the next module.</p><ol class="learning-list"><?php foreach ($highlights['quizzes'] as $quiz): ?><li><?= e($quiz) ?></li><?php endforeach; ?></ol></div></div></div><div class="text-center mt-5"><p class="text-secondary mb-3">Ready to put these skills into practice?</p><a href="enrollment.php?course_id=<?= e($course['id']) ?>" class="btn btn-primary btn-lg">Apply for this course <i class="bi bi-arrow-right ms-1"></i></a></div></div></section>
<?php $introCourse = $course; require __DIR__ . '/includes/academy-video.php'; ?>
<?php require __DIR__ . '/includes/footer.php'; ?>
