<?php
require_once __DIR__ . '/config/database.php';
$pageTitle = 'Courses';
$statement = $pdo->prepare('SELECT id, title, category, short_description, duration, level, image FROM courses WHERE status = :status ORDER BY title');
$statement->execute(['status' => 1]);
$courses = $statement->fetchAll();
$categories = array_values(array_unique(array_column($courses, 'category')));
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><span class="eyebrow text-info">Explore your potential</span><h1 class="mt-3">Courses for the digital world.</h1><p class="lead mb-0">Choose a practical path, learn by building and take your next step with confidence.</p></div></section>
<section class="section-space"><div class="container"><div class="filter-bar mb-5"><div class="row g-3 align-items-center"><div class="col-lg-7"><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input type="search" class="form-control" placeholder="Search courses..." data-filter-input></div></div><div class="col-lg-5"><select class="form-select" data-filter-category><option value="">All categories</option><?php foreach ($categories as $category): ?><option value="<?= e($category) ?>"><?= e($category) ?></option><?php endforeach; ?></select></div></div></div><div class="row g-4"><?php foreach ($courses as $course): ?><div class="col-md-6 col-lg-4" data-filter-item data-category="<?= e($course['category']) ?>"><article class="course-card h-100"><?php if (!empty($course['image'])): ?><img src="<?= e(image_url($course['image'])) ?>" class="w-100" alt="<?= e($course['title']) ?>"><?php else: ?><div class="placeholder-image"><i class="bi bi-mortarboard"></i></div><?php endif; ?><div class="card-body"><span class="badge badge-soft mb-2"><?= e($course['category']) ?></span><h4><?= e($course['title']) ?></h4><p class="text-secondary"><?= e($course['short_description']) ?></p><div class="meta d-flex flex-wrap gap-3"><span><i class="bi bi-clock me-1"></i><?= e($course['duration']) ?></span><span><i class="bi bi-bar-chart me-1"></i><?= e($course['level']) ?></span></div><div class="d-flex gap-2 mt-3"><a href="course-details.php?id=<?= e($course['id']) ?>" class="btn btn-sm btn-outline-primary">View Details</a><a href="enrollment.php?course_id=<?= e($course['id']) ?>" class="btn btn-sm btn-primary">Enroll Now</a></div></div></article></div><?php endforeach; ?></div><div class="empty-state" data-empty-state><i class="bi bi-search fs-2 d-block mb-2"></i>No courses match your search.</div><?php if (!$courses): ?><div class="empty-state d-block"><i class="bi bi-info-circle fs-2 d-block mb-2"></i>No active courses are available.</div><?php endif; ?></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
