<?php
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/functions.php';
$pageTitle = 'Fees Structure';
$feeStatement = $pdo->prepare('SELECT fees.id, fees.course_id, courses.title AS course_title, courses.category, fees.fee_type, fees.amount, fees.discount_amount, fees.duration, fees.description FROM fees INNER JOIN courses ON courses.id = fees.course_id WHERE fees.status = :fee_status AND courses.status = :course_status ORDER BY courses.title, fees.id');
$feeStatement->execute(['fee_status' => 1, 'course_status' => 1]);
$fees = $feeStatement->fetchAll();
$categories = array_values(array_unique(array_column($fees, 'category')));
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><span class="eyebrow text-info">Transparent pricing</span><h1 class="mt-3">Invest in your future.</h1><p class="lead mb-0">Simple, clear fees for practical courses that help you build your next opportunity.</p></div></section>
<section class="section-space"><div class="container"><div class="filter-bar mb-5"><div class="row g-3"><div class="col-lg-7"><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input type="search" class="form-control" placeholder="Search courses or fee types..." data-filter-input></div></div><div class="col-lg-5"><select class="form-select" data-filter-category><option value="">All categories</option><?php foreach ($categories as $category): ?><option value="<?= e($category) ?>"><?= e($category) ?></option><?php endforeach; ?></select></div></div></div><div class="row g-4"><?php foreach ($fees as $fee): ?><div class="col-md-6 col-lg-4" data-filter-item data-category="<?= e($fee['category']) ?>"><article class="info-card h-100 p-4"><span class="badge badge-soft mb-3"><?= e($fee['category']) ?></span><h4><?= e($fee['course_title']) ?></h4><p class="text-secondary small"><?= e($fee['fee_type']) ?></p><div class="my-3"><small class="text-secondary d-block">Original Fee</small><strong class="fs-3 text-primary">Rs. <?= e(number_format((float) $fee['amount'], 2)) ?></strong></div><div class="d-flex justify-content-between border-top pt-3 mb-2"><span class="text-secondary">Discount</span><strong class="text-success">Rs. <?= e(number_format((float) $fee['discount_amount'], 2)) ?></strong></div><p class="small text-secondary mb-1"><i class="bi bi-calendar3 me-2"></i><?= e($fee['duration']) ?></p><?php if (!empty($fee['description'])): ?><p class="small text-secondary mt-3"><?= e($fee['description']) ?></p><?php endif; ?><div class="d-flex gap-2 mt-4"><a href="course-details.php?id=<?= e($fee['course_id']) ?>" class="btn btn-sm btn-outline-primary">View Course</a><a href="enrollment.php?course_id=<?= e($fee['course_id']) ?>" class="btn btn-sm btn-primary">Enroll</a></div></article></div><?php endforeach; ?></div><div class="empty-state" data-empty-state><i class="bi bi-search fs-2 d-block mb-2"></i>No fee records match your search.</div><?php if (!$fees): ?><div class="empty-state d-block"><i class="bi bi-info-circle fs-2 d-block mb-2"></i>Fee details will be available soon.</div><?php endif; ?></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
