<?php
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/functions.php';
$pageTitle = 'Gallery';
$galleryStatement = $pdo->prepare('SELECT id, title, image, category, description FROM gallery WHERE status = :status ORDER BY created_at DESC, id DESC');
$galleryStatement->execute(['status' => 1]);
$items = $galleryStatement->fetchAll();
$categories = ['Classes', 'Students', 'Workshops', 'Events', 'Training', 'Projects', 'Certificates'];
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div class="container"><span class="eyebrow text-info">Inside the academy</span><h1 class="mt-3">Learning in action.</h1><p class="lead mb-0">A glimpse at our classes, workshops, projects and growing community.</p></div></section>
<section class="section-space"><div class="container"><div class="d-flex flex-wrap gap-2 justify-content-center mb-5" data-gallery-filters><button class="btn btn-primary btn-sm active" data-gallery-category="">All</button><?php foreach ($categories as $category): ?><button class="btn btn-outline-primary btn-sm" data-gallery-category="<?= e($category) ?>"><?= e($category) ?></button><?php endforeach; ?></div><div class="row g-4"><?php foreach ($items as $item): ?><div class="col-6 col-md-4" data-gallery-item data-category="<?= e($item['category']) ?>"><button type="button" class="gallery-item border-0 p-0 w-100 text-start bg-transparent" data-bs-toggle="modal" data-bs-target="#galleryModal" data-gallery-image="<?= e(image_url($item['image'], 'gallery')) ?>" data-gallery-title="<?= e($item['title']) ?>" data-gallery-description="<?= e($item['description'] ?? '') ?>"><div class="rounded-4 overflow-hidden position-relative gallery-frame"><img src="<?= e(image_url($item['image'], 'gallery')) ?>" class="w-100" style="height:240px;object-fit:cover" loading="lazy" alt="<?= e($item['title']) ?>"><div class="gallery-overlay"><i class="bi bi-zoom-in fs-3"></i></div></div><h5 class="mt-3 mb-1 small"><?= e($item['title']) ?></h5><small class="text-secondary"><?= e($item['category']) ?></small></button></div><?php endforeach; ?></div><div class="empty-state" data-gallery-empty><i class="bi bi-images fs-2 d-block mb-2"></i>No gallery items match this category.</div><?php if (!$items): ?><div class="empty-state d-block"><i class="bi bi-images fs-2 d-block mb-2"></i>Gallery items will be available soon.</div><?php endif; ?></div></section>
<div class="modal fade" id="galleryModal" tabindex="-1" aria-labelledby="galleryModalLabel" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content border-0 rounded-4 overflow-hidden"><div class="modal-header"><h5 class="modal-title" id="galleryModalLabel">Gallery preview</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><img id="galleryModalImage" src="assets/images/placeholder.svg" class="w-100" style="max-height:520px;object-fit:cover" alt=""><div class="modal-body"><h5 id="galleryModalTitle"></h5><p id="galleryModalDescription" class="text-secondary mb-0"></p></div></div></div></div>
<?php require __DIR__ . '/includes/footer.php'; ?>
