<?php
require_once __DIR__ . '/config/database.php';
$pageTitle = 'Learn Digital Skills. Build Your Future.';
$pageDescription = 'Practical training for the digital world.';
$courseStatement = $pdo->prepare('SELECT id, title, category, short_description, duration, level, image FROM courses WHERE status = :status ORDER BY id LIMIT 6');
$courseStatement->execute(['status' => 1]);
$courses = $courseStatement->fetchAll();
$serviceStatement = $pdo->prepare('SELECT title, description, icon, image FROM services WHERE status = :status ORDER BY id LIMIT 4');
$serviceStatement->execute(['status' => 1]);
$services = $serviceStatement->fetchAll();
$galleryStatement = $pdo->prepare('SELECT title, image, category FROM gallery WHERE status = :status ORDER BY id DESC LIMIT 4');
$galleryStatement->execute(['status' => 1]);
$gallery = $galleryStatement->fetchAll();
$enrollmentCountStatement = $pdo->prepare('SELECT COUNT(*) FROM enrollments');
$enrollmentCountStatement->execute();
$enrollmentCount = (int) $enrollmentCountStatement->fetchColumn();
$studentResponses = [
	['name' => 'Ayesha Khan', 'course' => 'Website Development', 'message' => 'The practical projects helped me understand web development much faster than theory alone.'],
	['name' => 'Bilal Ahmed', 'course' => 'Python Programming', 'message' => 'I started as a beginner and now I can build small Python tools with confidence.'],
	['name' => 'Hira Baloch', 'course' => 'Graphic Designing', 'message' => 'The design assignments gave me a portfolio I am proud to share with clients.'],
	['name' => 'Usman Raza', 'course' => 'Digital Marketing', 'message' => 'The SEO and campaign exercises made digital marketing feel practical and achievable.'],
	['name' => 'Sana Noor', 'course' => 'UI/UX Design', 'message' => 'I learned how to think about real users and turn ideas into clear prototypes.'],
	['name' => 'Hamza Ali', 'course' => 'Cyber Security', 'message' => 'The security lessons improved the way I protect my accounts and understand digital risks.'],
	['name' => 'Maham Shah', 'course' => 'Freelancing', 'message' => 'The proposal and portfolio guidance helped me present my skills professionally.'],
	['name' => 'Danish Iqbal', 'course' => 'Machine Learning', 'message' => 'The step-by-step data projects made a difficult subject easier to follow.'],
	['name' => 'Rabia Javed', 'course' => 'Video Editing', 'message' => 'I enjoyed every practical editing task and finished with a video I could show others.'],
	['name' => 'Zainab Noor', 'course' => 'E-Commerce', 'message' => 'The course helped me plan my online store and understand the customer journey.'],
];
require __DIR__ . '/includes/header.php';
?>
<section class="hero"><div class="container position-relative z-1"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="eyebrow">Future-ready learning</span><h1 class="mt-3">Learn Digital Skills. <span>Build Your Future.</span></h1><p class="lead my-4">Practical training for the digital world. Turn curiosity into confidence with guided learning, hands-on projects and skills that create opportunity.</p><a href="courses.php" class="btn btn-primary btn-lg me-2">Explore Courses <i class="bi bi-arrow-right ms-1"></i></a><a href="enrollment.php" class="btn btn-outline-primary btn-lg">Enroll Now</a></div><div class="col-lg-5"><div class="p-4 p-md-5 bg-white rounded-4 shadow-lg"><span class="eyebrow">Start today</span><h3 class="mt-3">Skills that move you forward.</h3><p class="text-secondary">Learn from a practical curriculum designed for the real digital world.</p><div class="d-flex align-items-center gap-3 mt-4"><div class="icon-box"><i class="bi bi-rocket-takeoff"></i></div><div><strong>Project-based learning</strong><small class="d-block text-secondary">Build while you learn</small></div></div><div class="d-flex align-items-center gap-3 mt-3"><div class="icon-box"><i class="bi bi-people"></i></div><div><strong>Supportive community</strong><small class="d-block text-secondary">Grow with guidance</small></div></div></div></div></div></div></section>
<section class="section-space"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><span class="eyebrow">About the academy</span><h2 class="section-title mt-3">Learn skills that create real opportunities.</h2><p class="section-copy mt-3">Digital Skills Academy helps students build practical, career-ready abilities through accessible training and real-world projects.</p><a href="about.php" class="btn btn-outline-primary mt-3">Discover our story <i class="bi bi-arrow-up-right"></i></a></div><div class="col-lg-6"><div class="row g-3"><div class="col-6"><div class="feature-card p-4"><div class="icon-box mb-3"><i class="bi bi-tools"></i></div><h5>Practical skills</h5><p class="small text-secondary mb-0">Learn by doing with guided exercises.</p></div></div><div class="col-6 mt-5"><div class="feature-card p-4"><div class="icon-box mb-3"><i class="bi bi-bar-chart"></i></div><h5>Career growth</h5><p class="small text-secondary mb-0">Build confidence for your next step.</p></div></div></div></div></div></div></section>
<section class="section-space section-soft"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><span class="eyebrow">Explore learning</span><h2 class="section-title mt-2 mb-0">Popular courses</h2></div><a href="courses.php" class="btn btn-outline-primary">View all courses</a></div><div class="row g-4"><?php foreach ($courses as $course): ?><div class="col-md-6 col-lg-4"><article class="course-card h-100"><?php if (!empty($course['image'])): ?><img src="<?= e(image_url($course['image'])) ?>" alt="<?= e($course['title']) ?>" class="w-100"><?php else: ?><div class="placeholder-image"><i class="bi bi-mortarboard"></i></div><?php endif; ?><div class="card-body"><span class="badge badge-soft mb-2"><?= e($course['category']) ?></span><h5><?= e($course['title']) ?></h5><p class="text-secondary small"><?= e($course['short_description']) ?></p><div class="meta d-flex justify-content-between"><span><i class="bi bi-clock me-1"></i><?= e($course['duration']) ?></span><span><i class="bi bi-bar-chart me-1"></i><?= e($course['level']) ?></span></div><a href="course-details.php?id=<?= e($course['id']) ?>" class="btn btn-sm btn-outline-primary mt-3">View Details</a></div></article></div><?php endforeach; ?></div><?php if (!$courses): ?><p class="text-center text-secondary mt-4">Courses will be available soon.</p><?php endif; ?></div></section>
<section class="section-space"><div class="container"><div class="text-center mb-5"><span class="eyebrow">How we help</span><h2 class="section-title mt-2">Our services</h2><p class="section-copy mx-auto">More than lessons—everything you need to turn digital skills into meaningful progress.</p></div><div class="row g-4"><?php foreach ($services as $service): ?><div class="col-md-6 col-lg-3"><div class="service-card h-100 p-4"><div class="icon-box mb-3"><i class="bi <?= e($service['icon'] ?: 'bi-stars') ?>"></i></div><h5><?= e($service['title']) ?></h5><p class="small text-secondary mb-0"><?= e($service['description']) ?></p></div></div><?php endforeach; ?></div></div></section>
<section class="stats-strip py-5"><div class="container"><div class="row text-center g-4"><div class="col-6 col-lg-3"><strong>12+</strong><span>Career-focused courses</span></div><div class="col-6 col-lg-3"><strong>100%</strong><span>Practical learning</span></div><div class="col-6 col-lg-3"><strong>5+</strong><span>Student support services</span></div><div class="col-6 col-lg-3"><strong><?= e($enrollmentCount) ?>+</strong><span>Learners enrolled</span></div></div></div></section>
<section class="section-space"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><span class="eyebrow">Inside the academy</span><h2 class="section-title mt-2 mb-0">Learning in action</h2></div><a href="gallery.php" class="btn btn-outline-primary">Visit gallery</a></div><div class="row g-3"><?php foreach ($gallery as $item): ?><div class="col-6 col-lg-3"><div class="rounded-4 overflow-hidden bg-light"><img src="<?= e(image_url($item['image'], 'gallery')) ?>" class="w-100" style="height:210px;object-fit:cover" alt="<?= e($item['title']) ?>"><div class="p-3"><strong class="small"><?= e($item['title']) ?></strong><small class="d-block text-secondary"><?= e($item['category']) ?></small></div></div></div><?php endforeach; ?></div></div></section>
<section class="section-space section-soft"><div class="container"><div class="text-center mb-5"><span class="eyebrow">Student voices</span><h2 class="section-title mt-2">What our learners say</h2><p class="section-copy mx-auto">Real progress starts with the right support, practice and encouragement.</p></div><div class="row g-4"><?php foreach ($studentResponses as $response): ?><div class="col-md-6 col-lg-4"><article class="response-card h-100 p-4"><div class="d-flex gap-1 text-warning mb-3" aria-label="Five star review"><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i><i class="bi bi-star-fill"></i></div><p class="mb-4">“<?= e($response['message']) ?>”</p><div class="d-flex align-items-center gap-3"><span class="avatar-mark"><?= e(strtoupper(substr($response['name'], 0, 1))) ?></span><div><strong><?= e($response['name']) ?></strong><small class="d-block text-secondary"><?= e($response['course']) ?></small></div></div></article></div><?php endforeach; ?></div></div></section>
<section class="pb-5"><div class="container"><div class="cta p-4 p-md-5"><div class="row align-items-center"><div class="col-lg-8"><h2>Ready to build your future?</h2><p class="mb-lg-0">Take the first step toward a practical, rewarding digital career.</p></div><div class="col-lg-4 text-lg-end mt-3 mt-lg-0"><a href="enrollment.php" class="btn btn-light btn-lg">Start learning <i class="bi bi-arrow-right"></i></a></div></div></div></div></section>
<?php require __DIR__ . '/includes/academy-video.php'; ?>
<?php require __DIR__ . '/includes/footer.php'; ?>
