<?php
require_once __DIR__ . '/../../includes/admin_auth.php'; require_admin();
$errors = [];
if (is_post_request()) {
	$title=post_string('title',150); $slug=slugify(post_string('slug',180) ?: $title); $category=post_string('category',100); $short=post_string('short_description',255); $description=post_string('description',5000); $duration=post_string('duration',100); $level=post_string('level',50); $status=isset($_POST['status'])?1:0;
	if (!verify_csrf_token($_POST['csrf_token'] ?? null)) $errors[]='Your form session expired. Please try again.';
	foreach (['title'=>'Title','category'=>'Category','short'=>'Short description','description'=>'Description','duration'=>'Duration','level'=>'Level'] as $value=>$label) if ($$value === '') $errors[]=$label.' is required.';
	$check=$pdo->prepare('SELECT id FROM courses WHERE slug=:slug LIMIT 1'); $check->execute(['slug'=>$slug]); if($check->fetch())$errors[]='That slug is already in use.';
	$image=upload_image('image','courses',$errors);
	if(!$errors){$insert=$pdo->prepare('INSERT INTO courses (title,slug,category,short_description,description,duration,level,image,status) VALUES (:title,:slug,:category,:short_description,:description,:duration,:level,:image,:status)');$insert->execute(['title'=>$title,'slug'=>$slug,'category'=>$category,'short_description'=>$short,'description'=>$description,'duration'=>$duration,'level'=>$level,'image'=>$image,'status'=>$status]);redirect('index.php');}
}
admin_header('Add Course','courses/index.php');
?><div class="card table-card"><div class="card-body p-4"><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?><div class="row g-3"><div class="col-md-8"><label class="form-label">Title *</label><input class="form-control" name="title" value="<?=old('title')?>" required></div><div class="col-md-4"><label class="form-label">Category *</label><input class="form-control" name="category" value="<?=old('category')?>" required></div><div class="col-md-8"><label class="form-label">Slug</label><input class="form-control" name="slug" value="<?=old('slug')?>"></div><div class="col-md-4"><label class="form-label">Image</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/gif,image/webp"><small class="text-secondary">Max 5 MB</small></div><div class="col-md-6"><label class="form-label">Duration *</label><input class="form-control" name="duration" value="<?=old('duration')?>" required></div><div class="col-md-6"><label class="form-label">Level *</label><input class="form-control" name="level" value="<?=old('level')?>" required></div><div class="col-12"><label class="form-label">Short Description *</label><input class="form-control" name="short_description" value="<?=old('short_description')?>" required></div><div class="col-12"><label class="form-label">Description *</label><textarea class="form-control" name="description" rows="7" required><?=old('description')?></textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="status" id="status" checked><label class="form-check-label" for="status">Active</label></div></div></div><div class="mt-4"><button class="btn btn-primary" type="submit">Save Course</button><a class="btn btn-outline-secondary ms-2" href="index.php">Cancel</a></div></form></div></div><?php admin_footer();?>
