<?php
require_once __DIR__ . '/../../includes/admin_auth.php'; require_admin(); $id=valid_id($_GET['id']??$_POST['id']??null); if($id===null)redirect('index.php'); $get=$pdo->prepare('SELECT * FROM courses WHERE id=:id LIMIT 1');$get->execute(['id'=>$id]);$course=$get->fetch();if(!$course)redirect('index.php');$errors=[];
if(is_post_request()){
	$title=post_string('title',150);$slug=slugify(post_string('slug',180)?:$title);$category=post_string('category',100);$short=post_string('short_description',255);$description=post_string('description',5000);$duration=post_string('duration',100);$level=post_string('level',50);$status=isset($_POST['status'])?1:0;
	if(!verify_csrf_token($_POST['csrf_token']??null))$errors[]='Your form session expired. Please try again.';foreach(['title'=>'Title','category'=>'Category','short'=>'Short description','description'=>'Description','duration'=>'Duration','level'=>'Level'] as $value=>$label)if($$value==='')$errors[]=$label.' is required.';$check=$pdo->prepare('SELECT id FROM courses WHERE slug=:slug AND id!=:id LIMIT 1');$check->execute(['slug'=>$slug,'id'=>$id]);if($check->fetch())$errors[]='That slug is already in use.';$image=upload_image('image','courses',$errors,$course['image']);
	if(!$errors){$update=$pdo->prepare('UPDATE courses SET title=:title,slug=:slug,category=:category,short_description=:short_description,description=:description,duration=:duration,level=:level,image=:image,status=:status WHERE id=:id');$update->execute(['title'=>$title,'slug'=>$slug,'category'=>$category,'short_description'=>$short,'description'=>$description,'duration'=>$duration,'level'=>$level,'image'=>$image,'status'=>$status,'id'=>$id]);redirect('index.php');}$course=array_merge($course,['title'=>$title,'slug'=>$slug,'category'=>$category,'short_description'=>$short,'description'=>$description,'duration'=>$duration,'level'=>$level,'image'=>$image,'status'=>$status]);
}
admin_header('Edit Course','courses/index.php');
?><div class="card table-card"><div class="card-body p-4"><form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?=e($id)?>"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?><div class="row g-3"><div class="col-md-8"><label class="form-label">Title *</label><input class="form-control" name="title" value="<?=e($course['title'])?>" required></div><div class="col-md-4"><label class="form-label">Category *</label><input class="form-control" name="category" value="<?=e($course['category'])?>" required></div><div class="col-md-8"><label class="form-label">Slug *</label><input class="form-control" name="slug" value="<?=e($course['slug'])?>" required></div><div class="col-md-4"><label class="form-label">Replace image</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/gif,image/webp"><small class="text-secondary">Max 5 MB</small></div><div class="col-md-6"><label class="form-label">Duration *</label><input class="form-control" name="duration" value="<?=e($course['duration'])?>" required></div><div class="col-md-6"><label class="form-label">Level *</label><input class="form-control" name="level" value="<?=e($course['level'])?>" required></div><div class="col-12"><label class="form-label">Short Description *</label><input class="form-control" name="short_description" value="<?=e($course['short_description'])?>" required></div><div class="col-12"><label class="form-label">Description *</label><textarea class="form-control" name="description" rows="7" required><?=e($course['description'])?></textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="status" id="status" <?=$course['status']?'checked':''?>><label class="form-check-label" for="status">Active</label></div></div></div><div class="mt-4"><button class="btn btn-primary" type="submit">Update Course</button><a class="btn btn-outline-secondary ms-2" href="index.php">Cancel</a></div></form></div></div><?php admin_footer();?>
