<?php
require_once __DIR__ . '/../../includes/admin_auth.php';require_admin();$id=valid_id($_GET['id']??$_POST['id']??null);if($id===null)redirect('index.php');$get=$pdo->prepare('SELECT * FROM fees WHERE id=:id LIMIT 1');$get->execute(['id'=>$id]);$fee=$get->fetch();if(!$fee)redirect('index.php');$courseStatement=$pdo->prepare('SELECT id,title FROM courses WHERE status=:status OR id=:id ORDER BY title');$courseStatement->execute(['status'=>1,'id'=>$fee['course_id']]);$courses=$courseStatement->fetchAll();$errors=[];
if(is_post_request()){
	$courseId=valid_id($_POST['course_id']??null);$feeType=post_string('fee_type',100);$amount=filter_var($_POST['amount']??null,FILTER_VALIDATE_FLOAT);$discount=filter_var($_POST['discount_amount']??null,FILTER_VALIDATE_FLOAT);$duration=post_string('duration',100);$description=post_string('description',3000);$status=isset($_POST['status'])?1:0;$courseIds=array_map('intval',array_column($courses,'id'));
	if(!verify_csrf_token($_POST['csrf_token']??null))$errors[]='Your form session expired. Please try again.';if($courseId===null||!in_array($courseId,$courseIds,true))$errors[]='Please select a valid course.';if($feeType==='')$errors[]='Fee type is required.';if($amount===false||$amount<0)$errors[]='Enter a valid original fee.';if($discount===false||$discount<0)$errors[]='Enter a valid discount amount.';if($amount!==false&&$discount!==false&&$discount>$amount)$errors[]='Discount cannot exceed the original fee.';if($duration==='')$errors[]='Duration is required.';
	if(!$errors){$update=$pdo->prepare('UPDATE fees SET course_id=:course_id,fee_type=:fee_type,amount=:amount,discount_amount=:discount_amount,duration=:duration,description=:description,status=:status WHERE id=:id');$update->execute(['course_id'=>$courseId,'fee_type'=>$feeType,'amount'=>$amount,'discount_amount'=>$discount,'duration'=>$duration,'description'=>$description?:null,'status'=>$status,'id'=>$id]);redirect('index.php');}$fee=array_merge($fee,['course_id'=>$courseId,'fee_type'=>$feeType,'amount'=>$amount===false?'':$amount,'discount_amount'=>$discount===false?'':$discount,'duration'=>$duration,'description'=>$description,'status'=>$status]);
}
admin_header('Edit Fee','fees/index.php');
?><div class="card table-card"><div class="card-body p-4"><form method="post"><input type="hidden" name="id" value="<?=e($id)?>"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?><div class="row g-3"><div class="col-md-6"><label class="form-label">Course *</label><select class="form-select" name="course_id" required><?php foreach($courses as $course):?><option value="<?=e($course['id'])?>" <?=((int)$fee['course_id']===(int)$course['id'])?'selected':''?>><?=e($course['title'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Fee Type *</label><input class="form-control" name="fee_type" value="<?=e($fee['fee_type'])?>" required></div><div class="col-md-4"><label class="form-label">Original Fee *</label><input class="form-control" type="number" name="amount" min="0" step="0.01" value="<?=e($fee['amount'])?>" required></div><div class="col-md-4"><label class="form-label">Discount *</label><input class="form-control" type="number" name="discount_amount" min="0" step="0.01" value="<?=e($fee['discount_amount'])?>" required></div><div class="col-md-4"><label class="form-label">Duration *</label><input class="form-control" name="duration" value="<?=e($fee['duration'])?>" required></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="5"><?=e($fee['description'])?></textarea></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="status" id="status" <?=$fee['status']?'checked':''?>><label class="form-check-label" for="status">Active</label></div></div></div><div class="mt-4"><button class="btn btn-primary" type="submit">Update Fee</button><a class="btn btn-outline-secondary ms-2" href="index.php">Cancel</a></div></form></div></div><?php admin_footer();?>
