<?php
/** Course-specific self-study material used by the syllabus and PDF download. */
$courseLearning = [
    'website-development' => ['outcomes' => ['Create responsive, accessible web pages', 'Build database-backed PHP features with PDO', 'Publish a complete portfolio website'], 'assignments' => ['Build a responsive landing page', 'Create a secure course catalog', 'Complete a multi-page academy website'], 'quizzes' => ['HTML, CSS and Bootstrap quiz', 'PHP, MySQL and security checkpoint']],
    'digital-marketing' => ['outcomes' => ['Plan campaigns for a target audience', 'Improve website visibility with SEO', 'Measure content and campaign performance'], 'assignments' => ['Create a 30-day content calendar', 'Perform a website SEO audit', 'Present a complete digital campaign'], 'quizzes' => ['Marketing foundations quiz', 'SEO and analytics checkpoint']],
    'graphic-designing' => ['outcomes' => ['Apply color, typography and layout principles', 'Create consistent brand visuals', 'Present client-ready design work'], 'assignments' => ['Design a personal brand identity', 'Create a social media design set', 'Present a visual portfolio'], 'quizzes' => ['Design principles quiz', 'Branding checkpoint']],
    'artificial-intelligence' => ['outcomes' => ['Explain core artificial intelligence concepts', 'Plan data-informed intelligent solutions', 'Apply responsible AI thinking'], 'assignments' => ['Map an AI solution for a real problem', 'Prepare a structured sample dataset', 'Design a responsible AI use case'], 'quizzes' => ['AI concepts quiz', 'Responsible AI checkpoint']],
    'machine-learning' => ['outcomes' => ['Prepare data for model training', 'Understand supervised learning workflows', 'Evaluate model results responsibly'], 'assignments' => ['Clean a sample dataset', 'Train a supervised model', 'Compare results and write findings'], 'quizzes' => ['Data preparation quiz', 'Model evaluation checkpoint']],
    'cyber-security' => ['outcomes' => ['Recognize common digital threats', 'Apply safer account and system practices', 'Create a practical defensive plan'], 'assignments' => ['Create a personal security checklist', 'Analyze a threat scenario', 'Write a defensive improvement plan'], 'quizzes' => ['Security fundamentals quiz', 'Threat awareness checkpoint']],
    'python-programming' => ['outcomes' => ['Write clear Python programs', 'Use functions and data structures', 'Build small useful automation tools'], 'assignments' => ['Build a command-line utility', 'Create a file-based data tool', 'Complete a small Python project'], 'quizzes' => ['Python logic quiz', 'Functions and data checkpoint']],
    'ui-ux-design' => ['outcomes' => ['Research user needs', 'Plan clear user flows and wireframes', 'Create and improve interactive prototypes'], 'assignments' => ['Interview users for a sample product', 'Create a wireframe and user flow', 'Present a clickable prototype'], 'quizzes' => ['User research quiz', 'Usability checkpoint']],
    'freelancing' => ['outcomes' => ['Build a professional freelancer profile', 'Write stronger proposals', 'Manage client communication and delivery'], 'assignments' => ['Create a freelancer profile', 'Write a client proposal', 'Build a service pricing plan'], 'quizzes' => ['Freelance profile quiz', 'Client communication checkpoint']],
    'e-commerce' => ['outcomes' => ['Plan an online store and product range', 'Understand customer journeys', 'Create practical store marketing plans'], 'assignments' => ['Plan a niche online store', 'Create product listings', 'Design a launch and customer-care plan'], 'quizzes' => ['E-commerce foundations quiz', 'Customer journey checkpoint']],
    'video-editing' => ['outcomes' => ['Organize and edit video footage', 'Use pacing, audio and titles effectively', 'Export web-ready video content'], 'assignments' => ['Edit a short story from raw clips', 'Create a titled social video', 'Export a portfolio reel'], 'quizzes' => ['Editing workflow quiz', 'Audio and export checkpoint']],
    'database-management' => ['outcomes' => ['Design reliable relational databases', 'Write useful SQL queries', 'Connect PHP forms safely with PDO'], 'assignments' => ['Design a relational course database', 'Write SQL reports', 'Connect a PHP form with PDO'], 'quizzes' => ['Database design quiz', 'SQL and safe access checkpoint']],
];
